### ISSUE TITLE
feedback for milestone 3

### ISSUE THREAD

**Issue by mkeyim** [UBC-MDS/violent_crimes_usa#12]
- font types different on different things
- scaling of line charts to be on same axis scale, it looks like there's more homicides than robberies
- bring up city selector
- good per capita use for maps
- Consider maybe a state selector before a city selector by wrangling out the state from the city name
- Can you default order to "total crime" in the rank table?
- can consider loading `library(shinyWidgets)` and using `pickerSelect` to have a "select all" and "deselect all" for doing your checkbox filter
- considering joining all 4 line charts into 1 chart by colour coding your crime type. This way there is no scrolling and it fixes the scaling issue

**Comment by Pall-v** [comment]
- I like the responsiveness of the map and how it snaps to specific zoom factors.
- You could associate the filters with the visualizations via vertical sectioning in a layout that doesn't use a sidebar.
- The Rank table is well laid-out.
- Ideally, the default sort order of the rank table would be the last column (the crime column)

**Comment by alyciakb** [comment]
Thank you for the feedback!
We completed the following changes: 
- merged 4 line plots into one plot
- brought up the city selector
- fixed the font issue

We attempted to address a few other issues, but hit bugs and couldn't due to time restraints.
